QUESTS = [
    {"name": "Animal Magnetism", "id": 0},
    {"name": "Another Slice of H.A.M.", "id": 1},
    {"name": "The Ascent of Arceuus", "id": 3},
    {"name": "Alfred Grimhand's Barcrawl", "id": 4},
    {"name": "Bear Your Soul", "id": 5},
    {"name": "Below Ice Mountain", "id": 6},
    {"name": "Between a Rock...", "id": 7},
    {"name": "Big Chompy Bird Hunting", "id": 8},
    {"name": "Biohazard", "id": 9},
    {"name": "Black Knights' Fortress", "id": 10},
    {"name": "Bone Voyage", "id": 11},
    {"name": "Cabin Fever", "id": 12},
    {"name": "Client of Kourend", "id": 13},
    {"name": "Clock Tower", "id": 14},
    {"name": "Cold War", "id": 15},
    {"name": "Contact!", "id": 16},
    {"name": "Cook's Assistant", "id": 17},
    {"name": "The Corsair Curse", "id": 18},
    {"name": "Creature of Fenkenstrain", "id": 19},
    {"name": "Curse of the Empty Lord", "id": 20},
    {"name": "Daddy's Home", "id": 21},
    {"name": "Darkness of Hallowvale", "id": 22},
    {"name": "Death Plateau", "id": 23},
    {"name": "Death to the Dorgeshuun", "id": 24},
    {"name": "Demon Slayer", "id": 25},
    {"name": "The Depths of Despair", "id": 26},
    {"name": "Desert Treasure I", "id": 27},
    {"name": "Devious Minds", "id": 28},
    {"name": "The Dig Site", "id": 29},
    {"name": "Doric's Quest", "id": 30},
    {"name": "Dragon Slayer I", "id": 31},
    {"name": "Dragon Slayer II", "id": 32},
    {"name": "Dream Mentor", "id": 33},
    {"name": "Druidic Ritual", "id": 34},
    {"name": "Dwarf Cannon", "id": 35},
    {"name": "Eadgar's Ruse", "id": 36},
    {"name": "Eagles' Peak", "id": 37},
    {"name": "Elemental Workshop I", "id": 38},
    {"name": "Elemental Workshop II", "id": 39},
    {"name": "Enakhra's Lament", "id": 40},
    {"name": "The Enchanted Key", "id": 41},
    {"name": "Enlightened Journey", "id": 42},
    {"name": "Enter the Abyss", "id": 43},
    {"name": "Ernest the Chicken", "id": 44},
    {"name": "The Eyes of Glouphrie", "id": 45},
    {"name": "Fairytale I - Growing Pains", "id": 46},
    {"name": "Fairytale II - Cure a Queen", "id": 47},
    {"name": "Family Crest", "id": 48},
    {"name": "Family Pest", "id": 49},
    {"name": "The Feud", "id": 50},
    {"name": "Fight Arena", "id": 51},
    {"name": "Fishing Contest", "id": 52},
    {"name": "Forgettable Tale...", "id": 53},
    {"name": "The Forsaken Tower", "id": 54},
    {"name": "The Fremennik Exiles", "id": 55},
    {"name": "The Fremennik Isles", "id": 56},
    {"name": "The Fremennik Trials", "id": 57},
    {"name": "Garden of Tranquillity", "id": 58},
    {"name": "The General's Shadow", "id": 59},
    {"name": "Gertrude's Cat", "id": 60},
    {"name": "Getting Ahead", "id": 61},
    {"name": "Ghosts Ahoy", "id": 62},
    {"name": "The Giant Dwarf", "id": 63},
    {"name": "Goblin Diplomacy", "id": 64},
    {"name": "The Golem", "id": 65},
    {"name": "The Grand Tree", "id": 66},
    {"name": "The Great Brain Robbery", "id": 67},
    {"name": "Grim Tales", "id": 68},
    {"name": "The Hand in the Sand", "id": 69},
    {"name": "Haunted Mine", "id": 70},
    {"name": "Hazeel Cult", "id": 71},
    {"name": "Heroes' Quest", "id": 72},
    {"name": "Holy Grail", "id": 73},
    {"name": "Horror from the Deep", "id": 74},
    {"name": "Icthlarin's Little Helper", "id": 75},
    {"name": "Imp Catcher", "id": 76},
    {"name": "In Aid of the Myreque", "id": 77},
    {"name": "In Search of Knowledge", "id": 78},
    {"name": "In Search of the Myreque", "id": 79},
    {"name": "Jungle Potion", "id": 80},
    {"name": "A Kingdom Divided", "id": 81},
    {"name": "King's Ransom", "id": 82},
    {"name": "The Knight's Sword", "id": 83},
    {"name": "Lair of Tarn Razorlor", "id": 84},
    {"name": "Legends' Quest", "id": 85},
    {"name": "Lost City", "id": 86},
    {"name": "The Lost Tribe", "id": 87},
    {"name": "Lunar Diplomacy", "id": 88},
    {"name": "Mage Arena I", "id": 89},
    {"name": "Mage Arena II", "id": 90},
    {"name": "Making Friends with My Arm", "id": 91},
    {"name": "Making History", "id": 92},
    {"name": "Merlin's Crystal", "id": 93},
    {"name": "Misthalin Mystery", "id": 94},
    {"name": "Monkey Madness I", "id": 95},
    {"name": "Monkey Madness II", "id": 96},
    {"name": "Monk's Friend", "id": 97},
    {"name": "Mountain Daughter", "id": 98},
    {"name": "Mourning's End Part I", "id": 99},
    {"name": "Mourning's End Part II", "id": 100},
    {"name": "Murder Mystery", "id": 101},
    {"name": "My Arm's Big Adventure", "id": 102},
    {"name": "Nature Spirit", "id": 103},
    {"name": "A Night at the Theatre", "id": 104},
    {"name": "Observatory Quest", "id": 105},
    {"name": "Olaf's Quest", "id": 106},
    {"name": "One Small Favour", "id": 107},
    {"name": "Pirate's Treasure", "id": 108},
    {"name": "Plague City", "id": 109},
    {"name": "A Porcine of Interest", "id": 110},
    {"name": "Priest in Peril", "id": 111},
    {"name": "Prince Ali Rescue", "id": 112},
    {"name": "The Queen of Thieves", "id": 113},
    {"name": "Rag and Bone Man I", "id": 114},
    {"name": "Rag and Bone Man II", "id": 115},
    {"name": "Ratcatchers", "id": 116},
    {"name": "Recipe for Disaster", "id": 117},
    {"name": "Recruitment Drive", "id": 118},
    {"name": "Regicide", "id": 119},
    {"name": "The Restless Ghost", "id": 120},
    {"name": "Romeo & Juliet", "id": 121},
    {"name": "Roving Elves", "id": 122},
    {"name": "Royal Trouble", "id": 123},
    {"name": "Rum Deal", "id": 124},
    {"name": "Rune Mysteries", "id": 125},
    {"name": "Scorpion Catcher", "id": 126},
    {"name": "Sea Slug", "id": 127},
    {"name": "Shades of Mort'ton", "id": 128},
    {"name": "Shadow of the Storm", "id": 129},
    {"name": "Sheep Herder", "id": 130},
    {"name": "Sheep Shearer", "id": 131},
    {"name": "Shield of Arrav", "id": 132},
    {"name": "Shilo Village", "id": 133},
    {"name": "Sins of the Father", "id": 134},
    {"name": "Skippy and the Mogres", "id": 135},
    {"name": "The Slug Menace", "id": 136},
    {"name": "Song of the Elves", "id": 137},
    {"name": "A Soul's Bane", "id": 138},
    {"name": "Spirits of the Elid", "id": 139},
    {"name": "Swan Song", "id": 140},
    {"name": "Tai Bwo Wannai Trio", "id": 141},
    {"name": "A Tail of Two Cats", "id": 142},
    {"name": "Tale of the Righteous", "id": 143},
    {"name": "A Taste of Hope", "id": 144},
    {"name": "Tears of Guthix", "id": 145},
    {"name": "Temple of Ikov", "id": 146},
    {"name": "Throne of Miscellania", "id": 147},
    {"name": "The Tourist Trap", "id": 148},
    {"name": "Tower of Life", "id": 149},
    {"name": "Tree Gnome Village", "id": 150},
    {"name": "Tribal Totem", "id": 151},
    {"name": "Troll Romance", "id": 152},
    {"name": "Troll Stronghold", "id": 153},
    {"name": "Underground Pass", "id": 154},
    {"name": "Vampyre Slayer", "id": 155},
    {"name": "Wanted!", "id": 156},
    {"name": "Watchtower", "id": 157},
    {"name": "Waterfall Quest", "id": 158},
    {"name": "What Lies Below", "id": 159},
    {"name": "Witch's House", "id": 160},
    {"name": "Witch's Potion", "id": 161},
    {"name": "X Marks the Spot", "id": 162},
    {"name": "Zogre Flesh Eaters", "id": 163},
    {"name": "The Frozen Door", "id": 164},
    {"name": "Land of the Goblins", "id": 165},
    {"name": "Hopespear's Will", "id": 166},
    {"name": "Temple of the Eye", "id": 167},
    {"name": "Beneath Cursed Sands", "id": 168},
    {"name": "Sleeping Giants", "id": 169},
    {"name": "The Garden of Death", "id": 180},
    {"name": "Into the Tombs", "id": 2306},
    {"name": "Recipe for Disaster - Another Cook's Quest", "id": 2307},
    {"name": "Recipe for Disaster - Mountain Dwarf", "id": 2308},
    {"name": "Recipe for Disaster - Wartface & Bentnoze", "id": 2309},
    {"name": "Recipe for Disaster - Pirate Pete", "id": 2310},
    {"name": "Recipe for Disaster - Lumbridge Guide", "id": 2311},
    {"name": "Recipe for Disaster - Evil Dave", "id": 2312},
    {"name": "Recipe for Disaster - Skrach Uglogwee", "id": 2313},
    {"name": "Recipe for Disaster - Sir Amik Varze", "id": 2314},
    {"name": "Recipe for Disaster - King Awowogei", "id": 2315},
    {"name": "Recipe for Disaster - Culinaromancer", "id": 2316},
    {"name": "Secrets of the North", "id": 2338},
    {"name": "Desert Treasure II - The Fallen Empire", "id": 2343},
    {"name": "His Faithful Servants", "id": 3250},
    {"name": "The Path of Glouphrie", "id": 3425},
    {"name": "Children of the Sun", "id": 3450},
    {"name": "Barbarian Training", "id": 3451},
    {"name": "Defender of Varrock", "id": 3466},
    {"name": "While Guthix Sleeps", "id": 3467},
    {"name": "Twilight's Promise", "id": 3512},
    {"name": "At First Light", "id": 3513},
    {"name": "Perilous Moons", "id": 3514},
    {"name": "The Ribbiting Tale of a Lily Pad Labour Dispute", "id": 3515},
]
